name: documentation

on: [push, pull_request]

permissions:
  contents: write

jobs:
  build-documentation:
    if: ${{ github.event_name == 'push' && github.ref_name == 'dev' }}
    runs-on: ubuntu-latest

    steps:
    - name: Install doxygen
      run: sudo apt install doxygen -y

    - name: Checkout
      uses: actions/checkout@v4

    - name: Create pages
      run: |
        doxygen doc/doxygen/doxydoc
    - name: Commit pages
      run: |
        git config --global --add safe.directory /
        GIT_STATUS=$(git status --porcelain)
        echo $GIT_STATUS
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        git add doc/
        if [ "$GIT_STATUS" != "" ]; then git commit -m "[AUTO] documentation generation" || echo "Nothing to commit"; fi
        if [ "$GIT_STATUS" != "" ]; then git push; fi

    - name: Update pages artifact
      id: deployment
      uses: actions/upload-pages-artifact@v3
      with:
        path: doc/doxygen/html

  deploy-documentation:
    if: ${{ github.event_name == 'push' && github.ref_name == 'dev' }}

    needs: build-documentation

    permissions:
      pages: write
      id-token: write

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
